version: "3"

tasks:

  ide-setup:
    desc: "Setup the project. Installs dependencies for IDE and more."
    cmds:
      - ln -s (which gopls) ~/.local/bin/gopls

  run:
    silent: true
    cmds:
      - >
        task --parallel --output=prefixed
        go-run
        templ-watch

  go-run:
    cmds:
      - cd internal/test && go tool air

  thx-gen:
    desc: "Generate the thx code for the project."
    cmds:
      - >
        cd internal/test
        && go tool thx generate routes -o gen/routes ./web/...

  templ-build:
    hidden: true
    silent: true
    prefix: "templ"
    cmds:
      - >
        cd internal/test
        && go tool templ generate

  templ-watch:
    hidden: true
    silent: true
    prefix: "proxy"
    env:
      TEMPL_DEV_MODE: true
    cmds:
      - >
        cd internal/test
        && go tool templ generate --watch --proxy=http://localhost:8642 --proxyport=9753 --open-browser=false
