version: "3"

tasks:

  ide-setup:
    desc: "Setup the project. Installs dependencies for IDE and more."
    cmds:
      - ln -s (which gopls) ~/.local/bin/gopls

  lint:
    desc: "Run the linter over the module."
    cmds:
      - golangci-lint run ./...

  test:
    desc: "Run the test suite with race detection."
    cmds:
      - go test -trimpath -buildvcs=false -failfast -count=1 -race ./...

  run:
    silent: true
    cmds:
      - >
        task --parallel --output=prefixed
        test-run
        test-thx-watch
        templ-watch

  test-run:
    cmds:
      - cd internal/test && go tool air

  test-copy-assets:
    desc: "Copy the assets to the build directory."
    cmds:
      - >
        cd internal/test
        && mkdir -p gen/assets
        && cp node_modules/htmx.org/dist/htmx.min.js gen/assets/htmx.min.js
        && cp node_modules/htmx.org/dist/ext/hx-ws.min.js gen/assets/hx-ws.min.js
        && cp node_modules/htmx.org/dist/ext/hx-sse.min.js gen/assets/hx-sse.min.js

  test-thx-build:
    desc: "Generate the thx code for the project."
    cmds:
      - >
        cd internal/test
        && go tool thx generate routes -o gen/routes ./web/...

  test-thx-watch:
    hidden: true
    silent: true
    prefix: "thx"
    cmds:
      - task --watch test-thx-build

  templ-build:
    hidden: true
    silent: true
    prefix: "templ"
    cmds:
      - >
        cd internal/test
        && go tool templ generate

  templ-watch:
    hidden: true
    silent: true
    prefix: "proxy"
    env:
      TEMPL_DEV_MODE: true
    cmds:
      - >
        cd internal/test
        && go tool templ generate --watch --proxy=http://localhost:8642 --proxyport=9753 --open-browser=false
