package codegen

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

// AssetEntry represents a static file with its path and content hash.
type AssetEntry struct {
	// FilePath is the URL path (e.g. "/assets/app.js").
	FilePath string
	// FuncName is the Go function name (e.g. "AppJs").
	FuncName string
	// Hash is the truncated content hash for cache busting.
	Hash string
}

// ScanAssets scans a directory and returns asset entries with content hashes.
func ScanAssets(dir string, urlPrefix string) ([]AssetEntry, error) {
	var entries []AssetEntry

	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		// Skip entries that go:embed * also excludes:
		// dotfiles (.*), underscore-prefixed (_*), testdata, and .go files.
		name := d.Name()
		if strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") || name == "testdata" {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			return nil
		}
		if strings.HasSuffix(name, ".go") {
			return nil
		}

		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		hash := sha256.Sum256(data)
		shortHash := fmt.Sprintf("%x", hash[:6])

		urlPath := urlPrefix
		if !strings.HasSuffix(urlPath, "/") {
			urlPath += "/"
		}
		urlPath += filepath.ToSlash(rel)

		entries = append(entries, AssetEntry{
			FilePath: urlPath,
			FuncName: fileToFuncName(filepath.ToSlash(rel)),
			Hash:     shortHash,
		})

		return nil
	})

	return entries, err
}

// GenerateAssetsFile generates a Go source file with functions for each asset.
func GenerateAssetsFile(entries []AssetEntry, pkgName string) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by github.com/go-thx/thx; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	for _, e := range entries {
		fmt.Fprintf(&buf, "func %s() string { return %q }\n", e.FuncName, e.FilePath+"?v="+e.Hash)
	}

	return format.Source(buf.Bytes())
}

// fileToFuncName converts a file path like "js/app.min.js" to "JsAppMinJs".
func fileToFuncName(path string) string {
	var b strings.Builder
	upper := true

	for _, r := range path {
		if r == '/' || r == '.' || r == '-' || r == '_' || r == ' ' {
			upper = true
			continue
		}
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upper = true
			continue
		}
		if upper {
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}

	name := b.String()
	if len(name) > 0 && unicode.IsDigit(rune(name[0])) {
		name = "F" + name
	}

	return name
}
