package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

func Generate(tree *RouteTree, pkgName string) ([]byte, error) {
	flattenGroups(tree)

	var buf bytes.Buffer

	buf.WriteString("// Code generated by github.com/go-thx/thx; DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	// pathJoin is defined in route.go, no extra imports needed

	for _, r := range tree.Routes {
		writeRouteFunc(&buf, "", r)
	}

	for _, g := range tree.Groups {
		writeGroup(&buf, "", g)
	}

	return format.Source(buf.Bytes())
}

func flattenGroups(tree *RouteTree) {
	flattenGroupsInner(&tree.Routes, &tree.Groups)
}

func flattenGroupsInner(routes *[]RouteEntry, groups *[]RouteGroup) {
	var remaining []RouteGroup
	for _, g := range *groups {
		flattenGroupsInner(&g.Routes, &g.Groups)

		if len(g.Groups) == 0 && allRootRoutes(g.Routes) {
			for _, r := range g.Routes {
				r.Path = g.Prefix
				*routes = append(*routes, r)
			}
		} else {
			remaining = append(remaining, g)
		}
	}
	*groups = remaining
}

func allRootRoutes(routes []RouteEntry) bool {
	for _, r := range routes {
		if r.Path != "/" {
			return false
		}
	}
	return true
}

func GenerateRouteFile(pkgName string) ([]byte, error) {
	src := fmt.Sprintf(`// Code generated by github.com/go-thx/thx; DO NOT EDIT.

package %s

import (
	"net/url"
	"strings"
)

type Route struct {
	path   string
	method string
	query  url.Values
}

func (r Route) Path() string {
	if len(r.query) > 0 {
		return r.path + "?" + r.query.Encode()
	}
	return r.path
}

func (r Route) Method() string { return r.method }

func (r Route) String() string { return r.Path() }

func (r Route) Query(key, value string) Route {
	if r.query == nil {
		r.query = make(url.Values)
	}
	r.query.Set(key, value)
	return r
}

func pathJoin(base string, parts ...string) string {
	return strings.TrimRight(base, "/") + "/" + strings.TrimLeft(strings.Join(parts, "/"), "/")
}
`, pkgName)

	return format.Source([]byte(src))
}

func writeRouteFunc(buf *bytes.Buffer, receiver string, r RouteEntry) {
	methodName := r.Name
	params := buildPathParams(r.PathParams)
	pathExpr := buildPathExpr(receiver, r.Path, r.PathParams)

	if receiver == "" {
		fmt.Fprintf(buf, "func %s(%s) Route {\n", methodName, params)
	} else {
		fmt.Fprintf(buf, "func (%s) %s(%s) Route {\n", receiver, methodName, params)
	}
	fmt.Fprintf(buf, "\treturn Route{path: %s, method: %q}\n", pathExpr, r.Method)
	buf.WriteString("}\n\n")
}

func writeGroup(buf *bytes.Buffer, parentReceiver string, g RouteGroup) {
	typeName := strings.ToLower(g.Name[:1]) + g.Name[1:]
	constructorName := g.Name

	if parentReceiver == "" {
		fmt.Fprintf(buf, "func %s() %s {\n", constructorName, typeName)
		fmt.Fprintf(buf, "\treturn %s{path: %q}\n", typeName, g.Prefix)
		buf.WriteString("}\n\n")
	} else {
		fmt.Fprintf(buf, "func (%s) %s() %s {\n", parentReceiver, constructorName, typeName)
		recvVar := strings.SplitN(parentReceiver, " ", 2)[0]
		fmt.Fprintf(buf, "\treturn %s{path: pathJoin(%s.path, %q)}\n", typeName, recvVar, g.Prefix)
		buf.WriteString("}\n\n")
	}

	fmt.Fprintf(buf, "type %s struct {\n\tpath string\n}\n\n", typeName)

	recvVar := strings.ToLower(typeName[:1])
	recv := fmt.Sprintf("%s %s", recvVar, typeName)

	for _, r := range g.Routes {
		writeRouteFunc(buf, recv, r)
	}

	for _, sg := range g.Groups {
		writeGroup(buf, recv, sg)
	}
}

func buildPathParams(params []PathParam) string {
	if len(params) == 0 {
		return ""
	}
	parts := make([]string, len(params))
	for i, p := range params {
		parts[i] = p.Name + " string"
	}
	return strings.Join(parts, ", ")
}

func buildPathExpr(receiver, routePath string, params []PathParam) string {
	if len(params) == 0 {
		if receiver == "" {
			return fmt.Sprintf("%q", routePath)
		}
		recvVar := strings.SplitN(receiver, " ", 2)[0]
		return fmt.Sprintf("pathJoin(%s.path, %q)", recvVar, routePath)
	}

	recvVar := ""
	if receiver != "" {
		recvVar = strings.SplitN(receiver, " ", 2)[0]
	}

	// Build path by replacing {param} with concatenation
	// e.g. "/users/{id}/posts" → pathJoin(p.path, "/users/", id, "/posts")
	segments := strings.Split(routePath, "/")
	var args []string

	if recvVar != "" {
		args = append(args, recvVar+".path")
	}

	var literal string
	for _, seg := range segments {
		if seg == "" {
			continue
		}
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			if literal != "" {
				args = append(args, fmt.Sprintf("%q", "/"+literal))
				literal = ""
			}
			paramName := seg[1 : len(seg)-1]
			args = append(args, fmt.Sprintf("%q", "/"))
			args = append(args, paramName)
		} else {
			if literal != "" {
				literal += "/" + seg
			} else {
				literal = seg
			}
		}
	}

	if literal != "" {
		args = append(args, fmt.Sprintf("%q", "/"+literal))
	}

	if len(args) == 1 {
		return args[0]
	}

	return strings.Join(args, " + ")
}

func hasGroups(tree *RouteTree) bool {
	return len(tree.Groups) > 0
}
