name: tests

on:
  push:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Mise
        uses: jdx/mise-action@v4
        with:
          install: true
          cache: true

      - name: Cache Go Modules
        uses: actions/cache@v6
        with:
          path: ~/go/pkg/mod
          key: go-modules-v1

      - name: Cache Go Build
        uses: actions/cache@v6
        with:
          path: ~/.cache/go-build
          key: go-build-v1

      - name: Test
        run: |
          go test \
          -coverprofile=coverage.txt -covermode=atomic \
          -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
